dist: trusty
sudo: false
language: cpp

env:
  - BUILD_DIR = wire_removal
    #  - BUILD_DIR = test

script:
  - ls
    #scripts:
    #  - compile
    #  - test

jobs:
    include:
      - stage: test
        script: skip
      - stage: compile
        script:
          - cd $BUILD_DIR
          - mkdir ./build
          - cd build
          - cmake ..
          - cmake --build . -- -j2
          - mv hacker_* ..
