dist: trusty
sudo: false
language: cpp

env:
  - BUILD_DIR = wire_removal
  - BUILD_DIR = test

stages:
  - compile
  - test

jobs:
    include:
      - stage: compile
                 
          env: 
            - BUILD_DIR = 1
            - BUILD_DIR = 2
        script:
          cd $BUILD_DIR
          - mkdir ./build
          - cd build
          - cmake ..
          - cmake --build . -- -j2
          - mv hacker_* ..

      - stage: test
           env:
           - PROBLEM_DIR = wire_removal
        script:
          ls #./test/hacker_test $PROBLEM_DIR
