dist: trusty
sudo: false
language: cpp

env:
  - BUILD_DIR = wire_removal
  - BUILD_DIR = test

jobs:
    include:
      - stage: test
            script:
              - cd $BUILD_DIR
              - mkdir ./build
              - cd build
              - cmake ..
              - cmake --build . -- -j2
              - mv hacker_* ..
       - stage: test
             script:
               - ./test/hacker_test $PROBLEM_DIR
stages:
  - compile
  - test
