dist: trusty
sudo: false
language: cpp

env:
  - BUILD_DIR = wire_removal
  - BUILD_DIR = travis

before_script:
  - cd test
  - mkdir ./build
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - mv hacker_test ..

script:
  - cd $BUILD_DIR
  - mkdir ./build
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - mv hacker_rank ..
  - ./test/hacker_rank $PROBLEM_DIR
