dist: trusty
sudo: false
language: cpp

env:
  - BUILD_DIR = wire_removal

jobs:
    include:
      - stage: compile
        script:
          cd $BUILD_DIR
          - mkdir ./build
          - cd build
          - cmake ..
          - cmake --build . -- -j2
          - mv hacker_* ..
      - stage: test
        script:
          ./test/hacker_test wire_removal
